### ISSUE TITLE
TypeError: can only concatenate list (not "Tensor") to list

### ISSUE THREAD

**Issue by slejeune** [gpengzhi/CrossConST-LLM#1]
While trying to finetune the model with cross-lingual consistency regularization I encountered an error in preprocessing the data. I am using the same data as given in this repository. The error appears to be caused by the way the dataset is created in `translation_dataset.py`, over which the ConcatDataset class is called in `finetuning.py` (line 183).

**Prompt:**
```
DATA=wmt_test-flores200_dev.cs_de_ru_zh.json
PROMPT=gpt-mt
ALPHA=0.1
CKPT=ALMA-13B-Pretrain-PEFT-MT-${PROMPT}-alpha01

torchrun --nnodes 1 --nproc_per_node 3 llama-recipes/examples/finetuning.py --dataset translation_dataset --prompt_type ${PROMPT} \
    --data_path ${DATA} \
    --model_name haoranxu/ALMA-13B-Pretrain \
    --num_epochs 1 --batch_size_training 4 \
    --lr 1e-4 --gradient_accumulation_steps 8 \
    --use_peft --peft_method lora --output_dir ${CKPT} \
    --enable_fsdp --use_fast_kernels \
    --xconst_alpha ${ALPHA} \
    1>logs/EXP.out 2>logs/EXP.err
```

**Stacktrace:**
```
W0723 15:05:07.619000 22987617682048 torch/distributed/run.py:757] 
W0723 15:05:07.619000 22987617682048 torch/distributed/run.py:757] *****************************************
W0723 15:05:07.619000 22987617682048 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0723 15:05:07.619000 22987617682048 torch/distributed/run.py:757] *****************************************
Loading checkpoint shards: 100%|██████████| 6/6 [00:16<00:00,  2.75s/it]
Loading checkpoint shards: 100%|██████████| 6/6 [00:16<00:00,  2.73s/it]
Loading checkpoint shards: 100%|██████████| 6/6 [00:16<00:00,  2.74s/it]
Preprocessing dataset:   0%|          | 0/105290 [00:00<?, ?it/s]
[rank2]: Traceback (most recent call last):
[rank2]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/examples/finetuning.py", line 8, in <module>
[rank2]:     fire.Fire(main)
[rank2]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
[rank2]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank2]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
[rank2]:     component, remaining_args = _CallAndUpdateTrace(
[rank2]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank2]:     component = fn(*varargs, **kwargs)
[rank2]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/finetuning.py", line 186, in main
[rank2]:     dataset_train = ConcatDataset(dataset_train, chunk_size=train_config.context_length)
[rank2]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in __init__
[rank2]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank2]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in <dictcomp>
[rank2]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank2]: TypeError: can only concatenate list (not "Tensor") to list
Preprocessing dataset:   0%|          | 0/105290 [00:00<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/examples/finetuning.py", line 8, in <module>
[rank0]:     fire.Fire(main)
[rank0]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
[rank0]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank0]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
[rank0]:     component, remaining_args = _CallAndUpdateTrace(
[rank0]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank0]:     component = fn(*varargs, **kwargs)
[rank0]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/finetuning.py", line 186, in main
[rank0]:     dataset_train = ConcatDataset(dataset_train, chunk_size=train_config.context_length)
[rank0]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in __init__
[rank0]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank0]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in <dictcomp>
[rank0]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank0]: TypeError: can only concatenate list (not "Tensor") to list
Preprocessing dataset:   0%|          | 0/105290 [00:00<?, ?it/s]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/examples/finetuning.py", line 8, in <module>
[rank1]:     fire.Fire(main)
[rank1]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
[rank1]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank1]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
[rank1]:     component, remaining_args = _CallAndUpdateTrace(
[rank1]:   File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
[rank1]:     component = fn(*varargs, **kwargs)
[rank1]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/finetuning.py", line 186, in main
[rank1]:     dataset_train = ConcatDataset(dataset_train, chunk_size=train_config.context_length)
[rank1]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in __init__
[rank1]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank1]:   File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 42, in <dictcomp>
[rank1]:     buffer = {k: v + sample[k] for k,v in buffer.items()}
[rank1]: TypeError: can only concatenate list (not "Tensor") to list
E0723 15:05:42.662000 22987617682048 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 720550) of binary: /mntdir2/suzan/MThesis/crossXenv/bin/python
Traceback (most recent call last):
  File "/mntdir2/suzan/MThesis/crossXenv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mntdir2/suzan/MThesis/crossXenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-23_15:05:42
  host      : leo.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 720551)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-23_15:05:42
  host      : leo.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 720552)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-23_15:05:42
  host      : leo.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 720550)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Do you know why this might be happening? Thank you in advance for the help!

**Comment by gpengzhi** [comment]
I'm sorry for not getting back to you sooner.

 Could you check your environment the same as listed in README? BTW, did you install the `llama-recipes` package locally in this repo?

**Comment by slejeune** [comment]
Admittedly I have previously been trying to run the code using Python 3.10 with PyTorch 2.4.0 because I was having trouble setting up the environment.
However, I wanted to make absolutely sure that this isn’t the problem, so through conda I was now able to install an environment with Python 3.8.5 and PyTorch 2.2.0. This also appears to be compatible with the CUDA version of the GPUs, so that should cause no further issue.

When I run the code as I described above using this environment, it unfortunately gives me the exact same error message.

I also installed the llama-recipes locally, if I do not do that it gives me an import error about that.

**Comment by gpengzhi** [comment]
Sorry about the confusion.

Do you install the `llama-recipes` provided in this repo instead of directly installing it from `meta-llama/llama-recipes`? 

I am asking this question because the line numbers in the error message do not match those in the `llama-recipes` in this repo.

**Comment by slejeune** [comment]
I followed the instructions in this repo, and I did not install anything consciously from `meta-llama/llama-recipes`, so I thought that it should be installed correctly.

I added some comments to debug which mess with the line numbers, but if I remove those I get the following:

```
Traceback (most recent call last):
  File "examples/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/finetuning.py", line 183, in main
    dataset_train = ConcatDataset(dataset_train, chunk_size=train_config.context_length)
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 24, in __init__
    buffer = {k: v + sample[k] for k,v in buffer.items()}
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 24, in <dictcomp>
    buffer = {k: v + sample[k] for k,v in buffer.items()}
TypeError: can only concatenate list (not "Tensor") to list
Preprocessing dataset:   0%|          | 0/105290 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "examples/finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/finetuning.py", line 183, in main
    dataset_train = ConcatDataset(dataset_train, chunk_size=train_config.context_length)
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 24, in __init__
    buffer = {k: v + sample[k] for k,v in buffer.items()}
  File "/mntdir2/suzan/MThesis/CrossConST-LLM/llama-recipes/src/llama_recipes/data/concatenator.py", line 24, in <dictcomp>
    buffer = {k: v + sample[k] for k,v in buffer.items()}
TypeError: can only concatenate list (not "Tensor") to list
[2024-08-09 19:01:56,197] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 910202) of binary: /home/suzan/.conda/envs/crossXenv5/bin/python
Traceback (most recent call last):
  File "/home/suzan/.conda/envs/crossXenv5/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.0', 'console_scripts', 'torchrun')())
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/suzan/.conda/envs/crossXenv5/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-09_19:01:56
  host      : leo.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 910203)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-09_19:01:56
  host      : leo.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 910204)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-09_19:01:56
  host      : leo.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 910202)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Are those line numbers closer to what you would expect if `llama-recipes` is installed correctly?

**Comment by Smu-Tan** [comment]
@slejeune 

It might be something like this (this can be wrong, better ask the author):

In translation_dataset.py,

        sample["input_ids"] = example.tolist()
        sample["labels"] = labels.tolist()
        sample["attention_mask"] = example_mask.tolist()
        sample["prompt_length"] = [len(prompt)]
        
        sample["input_ids_"] = example.tolist()
        sample["labels_"] = labels.tolist()
        sample["attention_mask_"] = example_mask.tolist()
        sample["prompt_length_"] = [len(prompt)]
        
In concatenator.py, 
             
        if 'input_ids_' in self.dataset[0]:
                 buffer = {
                "input_ids": [],
                "attention_mask": [],
                "labels": [],
                "prompt_length": [],
                "input_ids_": [],
                "attention_mask_": [],
                "labels_": [],
                "prompt_length_": [],
                }
        else:
            buffer = {
                "input_ids": [],
                "attention_mask": [],
                "labels": [],
                }

@gpengzhi I think for your code, it should be `batching_strategy='padding'`? Otherwise, the calculation of kl_loss (the start1, end1, start2, end2) part might be incorrect? Could you please check?

**Comment by gpengzhi** [comment]
Hi @slejeune and @Smu-Tan 

First I want to apologize for my late response.

@Smu-Tan is correct. `batching_strategy` should be set to be `padding`. And I think @slejeune 's issue should be automatically resolved by adopting this configuration (Do not need to modify `translation_dataset.py ` and `concatenator .py`).

**Comment by slejeune** [comment]
Thank you both so much! @gpengzhi @Smu-Tan 

After changing the `batching_stragegy` the code now works without problem, both for the dataset in this repo as well as my own dataset.
